export interface CropData {
  emoji: string;
  displayName: string;
  category: string;
  badgeColor: string;
  bgColor: string;
  description: string;
  season: string;
  waterNeeds: "Low" | "Medium" | "High" | "Very High";
  soilType: string;
  tips: string[];
  funFact: string;
}

export const CROP_INFO: Record<string, CropData> = {
  rice: {
    emoji: "🌾",
    displayName: "Rice",
    category: "Cereal",
    badgeColor: "bg-amber-100 text-amber-800",
    bgColor: "from-amber-50 to-yellow-50",
    description:
      "Rice is one of the world's most important staple crops, feeding more than half the global population. It thrives in warm, humid conditions with abundant water availability.",
    season: "Kharif (June – November)",
    waterNeeds: "High",
    soilType: "Clay or loamy soils with good water retention",
    tips: [
      "Maintain 5–10 cm of standing water during the vegetative stage",
      "Drain fields 10–14 days before harvest to aid ripening",
      "Transplant seedlings at 3–4 weeks old for best yields",
      "Apply split nitrogen doses: basal + tillering + panicle initiation",
      "Monitor continuously for blast disease and stem borers",
    ],
    funFact: "More than 3.5 billion people depend on rice for 20% of their daily calories.",
  },
  maize: {
    emoji: "🌽",
    displayName: "Maize (Corn)",
    category: "Cereal",
    badgeColor: "bg-yellow-100 text-yellow-800",
    bgColor: "from-yellow-50 to-orange-50",
    description:
      "Maize is a highly adaptable cereal crop used for food, animal feed, and industrial purposes. It requires well-drained fertile soil and moderate rainfall.",
    season: "Kharif & Rabi",
    waterNeeds: "Medium",
    soilType: "Well-drained loamy or sandy-loam soil",
    tips: [
      "Sow seeds 2–3 cm deep with 60–75 cm row spacing",
      "Irrigation at tasseling and silking stages is critical",
      "Top-dress with nitrogen at knee-height stage",
      "Control fall armyworm early — inspect plants daily",
      "Harvest when husks turn brown and kernels are firm",
    ],
    funFact: "Maize is the world's largest produced grain crop by volume.",
  },
  chickpea: {
    emoji: "🫘",
    displayName: "Chickpea",
    category: "Legume",
    badgeColor: "bg-orange-100 text-orange-800",
    bgColor: "from-orange-50 to-amber-50",
    description:
      "Chickpea is a protein-rich legume widely cultivated in semi-arid regions. It fixes atmospheric nitrogen, making it an excellent crop for soil health restoration.",
    season: "Rabi (October – March)",
    waterNeeds: "Low",
    soilType: "Well-drained sandy loam to loam soils",
    tips: [
      "Avoid waterlogging — chickpea is highly sensitive to excess moisture",
      "Inoculate seeds with Rhizobium to boost nitrogen fixation",
      "One pre-sowing irrigation is usually sufficient",
      "Control pod borer with timely insecticide application",
      "Harvest when leaves and pods turn yellow-brown",
    ],
    funFact: "Chickpea can fix 30–60 kg of nitrogen per hectare, reducing fertilizer needs.",
  },
  kidneybeans: {
    emoji: "🫘",
    displayName: "Kidney Beans",
    category: "Legume",
    badgeColor: "bg-red-100 text-red-800",
    bgColor: "from-red-50 to-rose-50",
    description:
      "Kidney beans are nutritious legumes named for their kidney shape. They thrive in moderate climates and well-drained soils, and are a staple in cuisines worldwide.",
    season: "Kharif (June – September)",
    waterNeeds: "Medium",
    soilType: "Fertile, well-drained loam or silt-loam",
    tips: [
      "Maintain soil temperature above 15°C at sowing",
      "Avoid overhead irrigation to reduce disease incidence",
      "Rhizobium inoculation improves yields significantly",
      "Watch for anthracnose and bean mosaic virus",
      "Supporting trellises can increase pod yield",
    ],
    funFact: "One cup of cooked kidney beans provides 15 g of protein.",
  },
  pigeonpeas: {
    emoji: "🫘",
    displayName: "Pigeon Peas",
    category: "Legume",
    badgeColor: "bg-lime-100 text-lime-800",
    bgColor: "from-lime-50 to-green-50",
    description:
      "Pigeon pea is a drought-tolerant legume widely grown in tropical and subtropical regions. It is an important food crop in South Asia and Africa.",
    season: "Kharif (June – January)",
    waterNeeds: "Low",
    soilType: "Well-drained loam, sandy loam, or black soils",
    tips: [
      "Intercrop with cereals for efficient land use",
      "Deep taproot makes it highly drought-resistant once established",
      "Minimal fertilizer needed due to nitrogen fixation",
      "One or two irrigations at flowering and pod fill stages",
      "Stagger harvests as pods mature asynchronously",
    ],
    funFact: "Pigeon pea roots extend up to 2 metres deep, improving soil structure.",
  },
  mothbeans: {
    emoji: "🫘",
    displayName: "Moth Beans",
    category: "Legume",
    badgeColor: "bg-yellow-100 text-yellow-700",
    bgColor: "from-yellow-50 to-lime-50",
    description:
      "Moth bean is an extremely drought-tolerant legume native to arid regions of India. It is grown in dry, hot climates where few other crops survive.",
    season: "Kharif (July – October)",
    waterNeeds: "Low",
    soilType: "Sandy loam to loam, even infertile soils",
    tips: [
      "Ideal for arid and semi-arid dryland farming",
      "Minimal or no irrigation required after establishment",
      "Harvest when 60–70% pods are mature to avoid shattering",
      "Crop residue is excellent livestock fodder",
      "Fixes nitrogen and improves soil fertility for subsequent crops",
    ],
    funFact: "Moth bean can yield in areas with as little as 250 mm of annual rainfall.",
  },
  mungbean: {
    emoji: "🫛",
    displayName: "Mung Bean",
    category: "Legume",
    badgeColor: "bg-green-100 text-green-800",
    bgColor: "from-green-50 to-emerald-50",
    description:
      "Mung bean is a short-duration, versatile legume used for food, sprouts, and green manure. It is highly nutritious and easy to grow across diverse climates.",
    season: "Kharif & Zaid",
    waterNeeds: "Low",
    soilType: "Well-drained sandy loam or loam",
    tips: [
      "Days to maturity: 60–75 days — short enough for multiple seasons",
      "2–3 irrigations at critical growth stages suffice",
      "Harvest early morning to minimize pod shattering losses",
      "Rhizobium inoculation reduces fertilizer needs",
      "Excellent green-manure crop when ploughed under",
    ],
    funFact: "Mung bean sprouts are one of the most nutritious, fastest-growing vegetable foods.",
  },
  blackgram: {
    emoji: "🫘",
    displayName: "Black Gram",
    category: "Legume",
    badgeColor: "bg-slate-100 text-slate-800",
    bgColor: "from-slate-50 to-zinc-50",
    description:
      "Black gram (urad dal) is a protein-rich legume crucial in South Asian cuisine. It grows best in warm, humid conditions and well-drained soils.",
    season: "Kharif & Rabi",
    waterNeeds: "Low",
    soilType: "Well-drained clay loam to sandy loam",
    tips: [
      "Sensitive to waterlogging — ensure good field drainage",
      "Inoculate seeds with Bradyrhizobium for best nitrogen fixation",
      "Two to three irrigations during dry spells improve yield",
      "Watch for yellow mosaic disease transmitted by whitefly",
      "Stagger harvest as pods don't ripen uniformly",
    ],
    funFact: "Black gram is the main ingredient in traditional Indian dishes like idli and dosa.",
  },
  lentil: {
    emoji: "🫘",
    displayName: "Lentil",
    category: "Legume",
    badgeColor: "bg-orange-100 text-orange-700",
    bgColor: "from-orange-50 to-red-50",
    description:
      "Lentil is one of the oldest cultivated legumes, prized for its high protein content. It grows best in cool, dry climates with moderate rainfall.",
    season: "Rabi (October – April)",
    waterNeeds: "Low",
    soilType: "Light, sandy loam to loam soils",
    tips: [
      "Cool temperatures (15–25°C) during grain fill improve yield",
      "Avoid alkaline soils — pH 6.0–7.5 is optimal",
      "Minimal irrigation needed; excess moisture causes root rot",
      "Rhizobium inoculation improves nitrogen fixation significantly",
      "Harvest when 70–80% pods are mature and brown",
    ],
    funFact: "Lentils have been cultivated for over 9,000 years, making them one of humanity's oldest crops.",
  },
  pomegranate: {
    emoji: "🍎",
    displayName: "Pomegranate",
    category: "Fruit",
    badgeColor: "bg-red-100 text-red-700",
    bgColor: "from-red-50 to-pink-50",
    description:
      "Pomegranate is a fruit shrub prized for its jewel-like arils and powerful antioxidants. It thrives in semi-arid conditions and is highly drought-resistant.",
    season: "Year-round (harvested July – January)",
    waterNeeds: "Low",
    soilType: "Well-drained loamy, sandy, or calcareous soils",
    tips: [
      "Withstands drought but drip irrigation significantly boosts yield",
      "Prune annually to maintain open canopy for light penetration",
      "Apply micronutrient sprays (Zinc, Boron) at flowering",
      "Fruit bagging prevents insect damage and improves color",
      "Bears fruit from year 3; peak production from year 5–10",
    ],
    funFact: "A single pomegranate can contain up to 1,400 seeds.",
  },
  banana: {
    emoji: "🍌",
    displayName: "Banana",
    category: "Fruit",
    badgeColor: "bg-yellow-100 text-yellow-700",
    bgColor: "from-yellow-50 to-lime-50",
    description:
      "Banana is one of the world's most popular fruits, thriving in tropical climates. It is a fast-growing herbaceous perennial that produces year-round.",
    season: "Year-round (harvested 10–12 months after planting)",
    waterNeeds: "High",
    soilType: "Fertile, well-drained loam with high organic matter",
    tips: [
      "Requires 25–50 mm water per week — use drip irrigation",
      "Heavy feeder: apply balanced NPK + micronutrients regularly",
      "De-bell and bag bunches to improve fruit size and quality",
      "Remove sucker shoots except one healthy follower",
      "Harvest bunches when ridges begin to round out",
    ],
    funFact: "Bananas are technically berries, while strawberries are not — botanically speaking.",
  },
  mango: {
    emoji: "🥭",
    displayName: "Mango",
    category: "Fruit",
    badgeColor: "bg-orange-100 text-orange-700",
    bgColor: "from-orange-50 to-yellow-50",
    description:
      "Mango is the 'King of Fruits', celebrated across tropical Asia. It is a long-lived tree that rewards patient farmers with decades of abundant harvests.",
    season: "Summer (March – June)",
    waterNeeds: "Low",
    soilType: "Deep, well-drained loam or alluvial soils",
    tips: [
      "Dry winter period induces flowering — avoid irrigation Nov–Jan",
      "Paclobutrazol soil drenching can regulate alternate bearing",
      "Apply potassium-rich fertilizer post-harvest to rebuild tree reserves",
      "Monitor closely for mango hopper and fruit fly attacks",
      "Harvest at mature green stage; flesh softens and sweetens off-tree",
    ],
    funFact: "A mango tree can live and bear fruit for over 300 years.",
  },
  grapes: {
    emoji: "🍇",
    displayName: "Grapes",
    category: "Fruit",
    badgeColor: "bg-purple-100 text-purple-800",
    bgColor: "from-purple-50 to-violet-50",
    description:
      "Grapes are versatile fruits grown for fresh consumption, raisins, juice, and wine. They thrive in areas with hot, dry summers and mild winters.",
    season: "Winter (January – April harvest)",
    waterNeeds: "Medium",
    soilType: "Well-drained, deep sandy loam or gravel-loam",
    tips: [
      "Annual pruning is essential — remove 85–90% of previous season's wood",
      "Drip irrigation with fertigation maximizes quality and yield",
      "Bunch thinning improves berry size and sugar content",
      "Gibberellic acid spray increases berry size in table varieties",
      "Control downy mildew and powdery mildew with preventive fungicide sprays",
    ],
    funFact: "It takes about 1.2 kg of grapes to produce one bottle of wine.",
  },
  watermelon: {
    emoji: "🍉",
    displayName: "Watermelon",
    category: "Fruit / Vegetable",
    badgeColor: "bg-green-100 text-green-700",
    bgColor: "from-green-50 to-red-50",
    description:
      "Watermelon is a warm-season cucurbit with 92% water content, making it one of the world's most beloved summer fruits. It needs warmth, sunshine, and space to sprawl.",
    season: "Summer (March – June)",
    waterNeeds: "Medium",
    soilType: "Sandy loam soils with good drainage",
    tips: [
      "Ideal soil temperature for germination: 25–35°C",
      "Reduce irrigation 7–10 days before harvest to concentrate sugar",
      "Use black plastic mulch to warm soil and suppress weeds",
      "Hand-pollinate early morning flowers when bee activity is low",
      "Test ripeness by knocking — a ripe melon gives a hollow thud",
    ],
    funFact: "Watermelon is native to the Kalahari Desert of Africa and was cultivated in Egypt over 5,000 years ago.",
  },
  muskmelon: {
    emoji: "🍈",
    displayName: "Muskmelon",
    category: "Fruit",
    badgeColor: "bg-amber-100 text-amber-700",
    bgColor: "from-amber-50 to-orange-50",
    description:
      "Muskmelon (cantaloupe) is a sweet, aromatic fruit that thrives in hot, dry climates. Its distinctive netted skin and orange flesh are signs of its ripeness.",
    season: "Summer (February – May)",
    waterNeeds: "Medium",
    soilType: "Sandy loam to loam soils, good drainage critical",
    tips: [
      "Stop irrigation 10–15 days before harvest for maximum sweetness",
      "Fruit slip (easy detachment from stem) indicates perfect ripeness",
      "Grow on raised beds or trellises to improve air circulation",
      "Aphid and whitefly control is important to prevent viral diseases",
      "Harvest early morning when temperatures are cooler",
    ],
    funFact: "Muskmelons get their name from their characteristic musky aroma when ripe.",
  },
  apple: {
    emoji: "🍎",
    displayName: "Apple",
    category: "Fruit",
    badgeColor: "bg-red-100 text-red-700",
    bgColor: "from-red-50 to-pink-50",
    description:
      "Apple is one of the most widely cultivated tree fruits, thriving in temperate climates with cold winters. It demands chilling hours for proper flowering and fruit set.",
    season: "Harvest: August – November",
    waterNeeds: "Medium",
    soilType: "Deep, well-drained loam or sandy loam, pH 6.0–7.5",
    tips: [
      "Most varieties need 1,000–1,500 chilling hours below 7°C",
      "Annual pruning maintains tree structure and fruit quality",
      "Thin excess fruitlets to 1 per cluster for large, premium apples",
      "Apply calcium sprays to prevent bitter pit disorder",
      "Store harvested apples at 0–4°C with 90–95% humidity",
    ],
    funFact: "There are over 7,500 known cultivars of apples grown worldwide.",
  },
  orange: {
    emoji: "🍊",
    displayName: "Orange",
    category: "Fruit",
    badgeColor: "bg-orange-100 text-orange-700",
    bgColor: "from-orange-50 to-yellow-50",
    description:
      "Orange is the world's most widely grown tree fruit, celebrated for its vitamin C content. It thrives in subtropical climates with distinct but mild seasons.",
    season: "Winter to Spring (November – March)",
    waterNeeds: "Medium",
    soilType: "Well-drained sandy loam to clay loam",
    tips: [
      "Avoid water stress during fruit development — causes peel disorders",
      "Micronutrient spray (Zinc, Manganese, Boron) boosts fruit quality",
      "Remove water sprouts inside the canopy annually",
      "Trifoliate orange rootstock improves cold hardiness",
      "Harvest at color break; do not delay as quality deteriorates on tree",
    ],
    funFact: "Brazil produces approximately 30% of the world's orange supply.",
  },
  papaya: {
    emoji: "🍈",
    displayName: "Papaya",
    category: "Fruit",
    badgeColor: "bg-orange-100 text-orange-600",
    bgColor: "from-orange-50 to-amber-50",
    description:
      "Papaya is a fast-growing tropical fruit that can bear fruit within 9–11 months of planting. It is rich in papain enzyme, used both as food and medicine.",
    season: "Year-round in tropics",
    waterNeeds: "Medium",
    soilType: "Well-drained, sandy loam, rich in organic matter",
    tips: [
      "Extremely sensitive to waterlogging — even 48 hours can kill plants",
      "Plant 3 seeds per pit; thin to 1 healthy plant after germination",
      "Ring spot virus is the major threat — use resistant varieties",
      "Stake young plants in windy locations to prevent lodging",
      "Harvest when fruit skin shows first yellow patches",
    ],
    funFact: "Papaya can bear fruit all year long, producing up to 100 fruits per tree per year.",
  },
  coconut: {
    emoji: "🥥",
    displayName: "Coconut",
    category: "Plantation",
    badgeColor: "bg-brown-100 text-amber-900",
    bgColor: "from-amber-50 to-yellow-50",
    description:
      "The coconut palm is called the 'Tree of Life' in tropical regions for its versatility — nearly every part is used. It thrives on coastal sandy soils and high humidity.",
    season: "Year-round (harvested monthly)",
    waterNeeds: "High",
    soilType: "Sandy loam alluvial soils, coastal laterites",
    tips: [
      "Requires 8 hours of bright sunshine per day for optimal growth",
      "Basin irrigation or drip irrigation at 45-day intervals",
      "Apply green leaves or coir pith mulch to conserve moisture",
      "Intercrop with cocoa, pepper, or banana for additional income",
      "Monitor for rhinoceros beetle and red palm weevil damage",
    ],
    funFact: "A single mature coconut palm can produce up to 200 coconuts per year.",
  },
  cotton: {
    emoji: "🌸",
    displayName: "Cotton",
    category: "Fibre Crop",
    badgeColor: "bg-sky-100 text-sky-800",
    bgColor: "from-sky-50 to-blue-50",
    description:
      "Cotton is the world's most important natural fibre crop, grown in warm regions across the globe. It requires a long frost-free growing season and moderate rainfall.",
    season: "Kharif (May – December)",
    waterNeeds: "Medium",
    soilType: "Deep black cotton soil (Vertisol) or loam",
    tips: [
      "Maintain plant population at 60,000–80,000 plants/ha for best yield",
      "Topping promotes boll retention on lower branches",
      "IPM essential: bollworm is the most economically damaging pest",
      "Bt cotton varieties greatly reduce insecticide use",
      "Harvest cotton bolls before dew to keep lint dry and clean",
    ],
    funFact: "One bale of cotton (~220 kg) can make 215 pairs of jeans.",
  },
  jute: {
    emoji: "🌿",
    displayName: "Jute",
    category: "Fibre Crop",
    badgeColor: "bg-green-100 text-green-700",
    bgColor: "from-green-50 to-teal-50",
    description:
      "Jute is a long, soft, shiny bast fibre used to make burlap, hessian, and twine. It thrives in warm, humid climates with heavy monsoon rainfall.",
    season: "Kharif (March – August)",
    waterNeeds: "High",
    soilType: "Well-drained alluvial or loamy soils with high organic matter",
    tips: [
      "Sow seeds broadcast at first rain; 45–60 days pre-rain sowing also works",
      "Thin plants to 7–8 cm apart for maximum fibre yield",
      "Harvest at early flowering for finest fibre quality",
      "Ret (soak) harvested stems in slow-moving water for 10–30 days",
      "Dry extracted fibre in shade to prevent discoloration",
    ],
    funFact: "Jute is the second most important plant fibre after cotton and is 100% biodegradable.",
  },
  coffee: {
    emoji: "☕",
    displayName: "Coffee",
    category: "Plantation",
    badgeColor: "bg-brown-100 text-amber-900",
    bgColor: "from-amber-50 to-orange-50",
    description:
      "Coffee is one of the world's most traded commodities, grown in the equatorial 'Coffee Belt'. It requires a specific microclimate of altitude, rainfall, and shade.",
    season: "Harvest: October – February",
    waterNeeds: "Medium",
    soilType: "Volcanic, deep, well-drained loam or clay-loam, pH 6.0–6.5",
    tips: [
      "Shade trees (Grevillea, Silver Oak) reduce thermal stress",
      "Irrigation during prolonged dry spells prevents flower drop",
      "Prune after harvest to remove non-bearing wood",
      "Pulping, fermenting, and washing must be done within hours of harvest",
      "Monitor for coffee berry borer — most damaging pest globally",
    ],
    funFact: "Coffee is the world's second most traded commodity after crude oil.",
  },
};

export function getCropData(cropName: string): CropData {
  const key = cropName.toLowerCase().replace(/\s+/g, "");
  return (
    CROP_INFO[key] ?? {
      emoji: "🌱",
      displayName:
        cropName.charAt(0).toUpperCase() + cropName.slice(1),
      category: "Crop",
      badgeColor: "bg-green-100 text-green-800",
      bgColor: "from-green-50 to-emerald-50",
      description:
        "This crop was recommended based on your soil and climate parameters.",
      season: "Varies by region",
      waterNeeds: "Medium",
      soilType: "Suitable for your soil conditions",
      tips: [
        "Follow local agricultural extension service guidance",
        "Maintain proper fertilisation based on soil test results",
        "Monitor regularly for pests and diseases",
      ],
      funFact: "Precision agriculture helps farmers optimise every field decision.",
    }
  );
}
